name: Develop
on:
  pull_request:
    branches: [ main ]
jobs:
  develop:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: hamsaqua/action/.github/actions/develop-core@main
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.STARTER_PAT }}
    runs-on: ubuntu-latest
