name: Develop
on:
  pull_request:
    branches: [ main ]
jobs:
  develop:
    steps:
      - uses: actions/checkout@v5
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_DEVELOP }}@main
        env:
          ACTOR: ${{ github.actor }}
          ORG: ${{ vars.ORG }}
          REPO: ${{ vars.REPO_BUNDLE }}
          TOKEN: ${{ secrets.PAT_BUNDLE }}
    runs-on: ubuntu-latest
