name: Develop
on:
  pull_request:
    branches: [ main ]
jobs:
  develop:
    steps:
      - uses: actions/checkout@v5
      - uses: ${{ vars.ACTION_REPO }}/.github/actions/${{ vars.DEVELOP_ACTION }}@main
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.STARTER_PAT }}
    runs-on: ubuntu-latest
