name: Publish
on:
  push:
    branches: [ main ]
jobs:
  publish:
    steps:
      - uses: actions/checkout@v5
      - uses: ${{ vars.REPO_ACTION }}/.github/actions/${{ vars.ACTION_PUBLISH }}@main
        with:
          module: <module>
          group: ${{ vars.GROUP }}
          org: ${{ vars.ORG }}
          desc: ${{ vars.DESCRIPTION }}
          repo: ${{ vars.REPO_BUNDLE }}
          event: ${{ vars.EVENT_PUBLISH }}
          core_pat: ${{ secrets.PAT_CORE }}
          bundle_pat: ${{ secrets.PAT_BUNDLE }}
    runs-on: ubuntu-latest
